(() => {
"use strict";
const $=id=>document.getElementById(id);const cfg=window.NEX_CONFIG;
const fmtPower=(w,latin=false)=>w>=1000?`${(w/1000).toFixed(1)} ${latin?"kW":"кВт"}`:`${Math.round(w)} ${latin?"W":"Вт"}`;
const setText=(id,v)=>{const el=$(id);if(el)el.textContent=v};
let storyIndex=0,storyRemaining=cfg.storyRotationSeconds||30,lastState=null;
function renderForecast(items=[]){$("forecastRows").innerHTML=items.slice(0,3).map(x=>`<div class="forecast-day"><span>${x.day}</span><b>${x.icon} +${x.high}°</b><small>+${x.low}°</small></div>`).join("")}
function storyPages(state){const events=(state.events||[]).filter(e=>e.priority>=2);const pages=[];for(let i=0;i<events.length;i+=5)pages.push(events.slice(i,i+5));if(state.summaries?.length)pages.push(state.summaries);return pages.filter(Boolean)}
function renderStory(state){const pages=storyPages(state),rail=$("storyRail");if(!pages.length){rail.classList.add("is-hidden");return}rail.classList.remove("is-hidden");storyIndex%=pages.length;$("storyPage").innerHTML=pages[storyIndex].map(e=>`<div class="story-item"><span class="icon">${e.icon||"•"}</span><time>${e.time||""}</time><div><b>${e.title}</b><small>${e.detail||""}</small></div></div>`).join("");$("storyDots").innerHTML=pages.map((_,i)=>`<i class="${i===storyIndex?"active":""}"></i>`).join("")}
function renderFlows(s){$("flowGrid").classList.toggle("is-off",!s.grid.online||Math.abs(s.grid.power)<30);$("flowSolar").classList.toggle("is-off",s.solar.power<30);$("flowHouse").classList.toggle("is-off",s.house.power<30);const b=$("flowBattery");b.classList.toggle("is-off",Math.abs(s.battery.power)<30);b.classList.toggle("reverse",s.battery.power<0)}
function phrase(s){if(!s.grid.online)return"Світло зникло. Будинок перейшов на батарею.";if(!s.internet.online)return"Космос сьогодні мовчить.";if(s.solar.power>s.house.power)return"Сонце живить будинок.";return"Усі системи працюють нормально."}
function render(s){lastState=s;setText("gridVoltage",`${Math.round(s.grid.voltage)} В`);setText("gridPower",fmtPower(s.grid.power));setText("internetStatus",s.internet.online?"Online":"Offline");setText("internetPing",`${Math.round(s.internet.ping)} ms`);setText("solarPower",fmtPower(s.solar.power));setText("solarToday",`Сьогодні: ${s.solar.today} кВт·год`);setText("housePower",fmtPower(s.house.power));setText("deyePower",fmtPower(s.inverter.power));setText("deyeMode",s.inverter.mode);setText("batterySoc",`${Math.round(s.battery.soc)}%`);setText("batteryRuntime",`≈ ${Math.round(s.battery.runtimeHours)} год`);setText("weatherTemp",`${s.weather.temperature>=0?"+":""}${Math.round(s.weather.temperature)}°`);setText("weatherState",s.weather.state);renderForecast(s.weather.forecast);renderStory(s);renderFlows(s);document.body.classList.toggle("grid-offline",!s.grid.online);document.body.classList.toggle("internet-offline",!s.internet.online)}
function clock(){const n=new Date();setText("clock",n.toLocaleTimeString("uk-UA",{hour:"2-digit",minute:"2-digit"}));setText("date",n.toLocaleDateString("uk-UA",{weekday:"long",day:"numeric",month:"long"}))}
setInterval(clock,1000);clock();
setInterval(()=>{if(!lastState)return;storyRemaining--;if(storyRemaining<=0){storyRemaining=cfg.storyRotationSeconds||30;const pages=storyPages(lastState);if(pages.length){storyIndex=(storyIndex+1)%pages.length;renderStory(lastState)}}setText("storyCountdown",`Оновлення через ${storyRemaining} сек`)},1000);
function demo(){setInterval(()=>{const c=HouseState.get();HouseState.set({solar:{power:Math.max(0,c.solar.power+(Math.random()-.48)*150)},house:{power:Math.max(180,c.house.power+(Math.random()-.5)*70)},inverter:{power:Math.max(c.house.power,c.solar.power)},internet:{ping:Math.max(8,c.internet.ping+(Math.random()-.5)*3)}})},5000)}
function applyStates(list){const map=Object.fromEntries(list.map(x=>[x.entity_id,x])),c=HouseState.get();const num=(k,f)=>{const n=Number(map[cfg.entities[k]]?.state);return Number.isFinite(n)?n:f};const bool=(k,f)=>{const e=map[cfg.entities[k]];return e?["on","online","true","1","home"].includes(String(e.state).toLowerCase()):f};const weather=map[cfg.entities.weather];HouseState.set({grid:{voltage:num("gridVoltage",c.grid.voltage),online:bool("gridOnline",c.grid.online),power:num("gridPower",c.grid.power)},solar:{power:num("solarPower",c.solar.power),today:num("solarToday",c.solar.today)},house:{power:num("housePower",c.house.power)},inverter:{power:num("inverterPower",c.inverter.power),mode:map[cfg.entities.inverterMode]?.state||c.inverter.mode},battery:{soc:num("batterySoc",c.battery.soc),runtimeHours:num("batteryRuntime",c.battery.runtimeHours),power:num("batteryPower",c.battery.power)},internet:{ping:num("internetPing",c.internet.ping),online:bool("internetOnline",c.internet.online)},weather:weather?{temperature:Number(weather.attributes.temperature??c.weather.temperature),state:weather.state||c.weather.state,forecast:c.weather.forecast}:c.weather})}
function connectHA(){const url=cfg.homeAssistant.url||`${location.protocol==="https:"?"wss":"ws"}://${location.host}/api/websocket`;const ws=new WebSocket(url);let id=1;ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==="auth_required")ws.send(JSON.stringify({type:"auth",access_token:cfg.homeAssistant.token}));else if(m.type==="auth_ok")ws.send(JSON.stringify({id:id++,type:"get_states"}));else if(m.type==="result"&&Array.isArray(m.result)){applyStates(m.result);ws.send(JSON.stringify({id:id++,type:"subscribe_events",event_type:"state_changed"}))}else if(m.type==="event"&&m.event?.data?.new_state)applyStates([m.event.data.new_state])};ws.onclose=()=>setTimeout(connectHA,5000)}
HouseState.subscribe(render);if(cfg.demoMode)demo();else connectHA();
})();
