(() => {
"use strict";
const $=id=>document.getElementById(id), cfg=window.NEX_CONFIG;
const stage=$("stage");
const state={gridVoltage:230,gridOnline:true,solarPower:1800,housePower:820,batterySoc:82,batteryRuntime:13,batteryPower:430,internetPing:27,internetOnline:true,weatherTemp:18,weatherState:"Хмарно",todayOutages:1,todayBlackout:"2 хв",todaySolar:6.4,todayHouse:4.9,todayBattery:9,events:[{time:"08:41",title:"Сонце прокинулося",detail:"Панелі почали генерацію"},{time:"08:18",title:"Мережа стабільна",detail:"Напруга повернулась у норму"},{time:"07:42",title:"Будинок прокинувся",detail:"Споживання зросло до 820 Вт"}]};
function fit(){const s=Math.min(innerWidth/1920,innerHeight/1080);stage.style.transform=`translate(${(innerWidth-1920*s)/2}px,${(innerHeight-1080*s)/2}px) scale(${s})`}addEventListener("resize",fit);fit();
function fmtPower(w){return w>=1000?`${(w/1000).toFixed(1)} кВт`:`${Math.round(w)} Вт`}
function events(){ $("eventRows").innerHTML=state.events.slice(0,3).map(e=>`<div class="event"><time>${e.time}</time><p>${e.title}<small>${e.detail}</small></p></div>`).join("") }
function render(){
 $("gridVoltage").textContent=`${Math.round(state.gridVoltage)} V`;$("gridStatus").textContent=state.gridOnline?"Мережа є":"Автономно";$("internetStatus").textContent=state.internetOnline?`Online · ${Math.round(state.internetPing)} ms`:"Offline";
 $("solarPower").textContent=fmtPower(state.solarPower);$("inverterPower").textContent=fmtPower(state.solarPower);$("batteryRuntime").textContent=`≈ ${Math.round(state.batteryRuntime)} год`;$("housePower").textContent=fmtPower(state.housePower);
 $("solarDock").textContent=fmtPower(state.solarPower).replace("кВт","kW").replace("Вт","W");$("deyeDock").textContent=fmtPower(Math.max(state.housePower,state.solarPower)).replace("кВт","kW").replace("Вт","W");$("batterySoc").textContent=`${Math.round(state.batterySoc)}%`;$("houseDock").textContent=fmtPower(state.housePower).replace("кВт","kW").replace("Вт","W");
 $("footerGrid").textContent=state.gridOnline?"Online":"Автономно";$("footerInternet").textContent=state.internetOnline?"Online":"Offline";$("footerSolar").textContent=fmtPower(state.solarPower);$("footerBattery").textContent=`≈ ${Math.round(state.batteryRuntime)} год`;$("footerHouse").textContent=fmtPower(state.housePower);
 $("weatherTemp").textContent=`${state.weatherTemp>=0?"+":""}${Math.round(state.weatherTemp)}°`;$("weatherState").textContent=state.weatherState;
 $("todayOutages").textContent=state.todayOutages;$("todayBlackout").textContent=state.todayBlackout;$("todaySolar").textContent=`${state.todaySolar} кВт·год`;$("todayHouse").textContent=`${state.todayHouse} кВт·год`;$("todayBattery").textContent=`${state.todayBattery}%`;events();
 const phrase=!state.gridOnline?"Світло пішло. Я вже перевів будинок на батарею.":!state.internetOnline?"Космос сьогодні мовчить.":state.solarPower>state.housePower?"Сонце сьогодні старається.":"Поки все спокійно.";$("nexSpeech").textContent=phrase;$("nex").classList.add("talking");clearTimeout(render.t);render.t=setTimeout(()=>$("nex").classList.remove("talking"),7000)
}
function clock(){const d=new Date();$("clock").textContent=d.toLocaleTimeString("uk-UA",{hour:"2-digit",minute:"2-digit"});$("date").textContent=d.toLocaleDateString("uk-UA",{weekday:"long",day:"numeric",month:"long"})}setInterval(clock,1000);clock();
function demo(){render();setInterval(()=>{state.solarPower=Math.max(0,state.solarPower+(Math.random()-.48)*180);state.housePower=Math.max(180,state.housePower+(Math.random()-.5)*90);state.internetPing=Math.max(8,state.internetPing+(Math.random()-.5)*4);render()},5000)}
async function connectHA(){const url=cfg.homeAssistant.url||`${location.protocol==="https:"?"wss":"ws"}://${location.host}/api/websocket`;const ws=new WebSocket(url);let id=1;ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==="auth_required")ws.send(JSON.stringify({type:"auth",access_token:cfg.homeAssistant.token}));else if(m.type==="auth_ok")ws.send(JSON.stringify({id:id++,type:"get_states"}));else if(m.type==="result"&&Array.isArray(m.result)){apply(m.result);ws.send(JSON.stringify({id:id++,type:"subscribe_events",event_type:"state_changed"}))}else if(m.type==="event"&&m.event?.data?.new_state)apply([m.event.data.new_state])};ws.onclose=()=>setTimeout(connectHA,5000)}
function apply(list){const map=Object.fromEntries(list.map(s=>[s.entity_id,s]));const num=(k,v)=>map[cfg.entities[k]]?Number(map[cfg.entities[k]].state):v;const bool=(k,v)=>map[cfg.entities[k]]?["on","online","true","1","home"].includes(String(map[cfg.entities[k]].state).toLowerCase()):v;state.gridVoltage=num("gridVoltage",state.gridVoltage);state.gridOnline=bool("gridOnline",state.gridOnline);state.solarPower=num("solarPower",state.solarPower);state.housePower=num("housePower",state.housePower);state.batterySoc=num("batterySoc",state.batterySoc);state.batteryRuntime=num("batteryRuntime",state.batteryRuntime);state.internetPing=num("internetPing",state.internetPing);state.internetOnline=bool("internetOnline",state.internetOnline);const w=map[cfg.entities.weather];if(w){state.weatherTemp=Number(w.attributes.temperature??state.weatherTemp);state.weatherState=w.state||state.weatherState}render()}
cfg.demoMode?demo():connectHA();
})();
